name: Clang Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  clang-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update
        run: sudo apt-get update

      - name: Install clang-format
        run: sudo apt-get install git clang-format -y

      - name: Check code format
        run: |
          find . -regex '.*\.\(cpp\|h\|hpp\|c\)' -exec clang-format -style=file -i {} \;

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git diff --exit-code || (
            git add . &&
            git commit -m "Auto-format code using clang-format" &&
            git push
          )
